extern "C" {
const char* py_open();
const char* py_mute();
const char* py_unmute();
const char* py_set_python();
const char* py_keep_compatibility();
const char* py_close();
const char* py_coast();
const char* py_grib();
const char* py_metagrib();
const char* py_knowndrivers();
const char* py_mapgen();
const char* py_line();
const char* py_legend();
const char* py_odb();
const char* py_import();
const char* py_overlay();
const char* py_netcdf();
const char* py_metanetcdf();
const char* py_metainput();
const char* py_cont();
const char* py_input();
const char* py_table();
const char* py_obs();
const char* py_raw();
const char* py_image();
const char* py_plot();
const char* py_text();
const char* py_wind();
const char* py_symb();
const char* py_boxplot();
const char* py_tile();
const char* py_taylor();
const char* py_tephi();
const char* py_geojson();
const char* py_wrepjson();
const char* py_epsinput();
const char* py_epscloud();
const char* py_metgraph();
const char* py_metbufr();
const char* py_epsgraph();
const char* py_epswave();
const char* py_epswind();
const char* py_epsbar();
const char* py_epsshading();
const char* py_epsplumes();
const char* py_epslight();
const char* py_new(const char* page) ;
const char* py_reset(const char* name) ;
const char* py_setc(const char* name, const char* value) ;
const char* py_setr(const char* name, const double value) ;
const char* py_seti(const char* name, const int value) ;
const char* py_set1r(const char* name, const double* data, const int dim1) ;
const char* py_set2r(const char* name, const double* data, const int dim1, const int dim2) ;
const char* py_set1i(const char* name, const int* data, const int dim1) ;
const char* py_set2i(const char* name, const int* data, const int dim1, const int dim2) ;
const char* py_set1c(const char* name, const char** data, const int dim1) ;
};
