name: Notify ecmwflibs

on:
  push:
    branches: [ develop ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: mvasigh/dispatch-action@main
      with:
          token: ${{ secrets.NOTIFY_ECMWFLIBS }}
          repo: ecmwflibs
          owner: ecmwf
          event_type: magics-updated
